#!/bin/sh

BASEDIR=`dirname $(readlink -f $0)`

# Create symlinks to vim configuration
VIMRC="$HOME/.vimrc"
if [ ! -f $VIMRC ]; then
  ln -s $BASEDIR/src/vimrc $VIMRC
else
  echo "$VIMRC file already exists; skipping"
fi
VIMDIR="$HOME/.vim"
if [ ! -d $VIMDIR ]; then
    ln -s $BASEDIR/src/vim $VIMDIR
else
  echo "$VIMDIR directory already exists; skipping"
fi

# Create symlink to xmobarrc
# http://projects.haskell.org/xmobar/
XMOBARRC="$HOME/.xmobarrc"
if [ ! -f $XMOBARRC ]; then
  ln -s $BASEDIR/src/xmobarrc $XMOBARRC
else
  echo "$XMOBARRC file already exists; skipping"
fi

# Create symlink to xmonad configuration
XMONADDIR="$HOME/.xmonad"
if [ ! -d $XMONADDIR ]; then
  ln -s $BASEDIR/src/xmonad $XMONADDIR
else
  echo "$XMONADDIR directory already exists; skipping"
fi
