#!/bin/sh

BASEDIR=`dirname $(readlink -f $0)`

# Create symlinks to vim configuration
VIMRC="$HOME/.vimrc"
if [ ! -f $VIMRC ]; then
  ln -s $BASEDIR/src/vimrc $VIMRC
else
  echo "$VIMRC already exists; skipping"
fi
VIMDIR="$HOME/.vim"
if [ ! -d $VIMDIR ]; then
    ln -s $BASEDIR/src/vim $VIMDIR
else
  echo "$VIMDIR already exists; skipping"
fi

# Create symlink to xmobarrc
# http://projects.haskell.org/xmobar/
XMOBARRC="$HOME/.xmobarrc"
if [ ! -f $XMOBARRC ]; then
  ln -s $BASEDIR/src/xmobarrc $XMOBARRC
else
  echo "$XMOBARRC already exists; skipping"
fi
