#!/bin/sh

# I use ghcup to manage $PATH, so I specify the full path of the system-wide
# ghc that is installed by apt
exec /usr/bin/ghc \
    --make xmonad.hs \
    -i               \
    -ilib            \
    -fforce-recomp   \
    -main-is main    \
    -v0              \
    -o "$1"
