alias ll='ls -lcF'
alias la='ll -A'
alias px='ps auxw'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias less='less -r'
    alias vless='vim -u /usr/local/share/vim/vim73/macros/less.sh'
fi
