set -g default-terminal "ansi"
set-window-option -g utf8 on

# Use C-a instead of C-b as prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Toggle status bar
bind-key b set status

# Renumber windows automatically
set-option -g renumber-windows on

# Next and previous windows
bind-key Right next-window
bind-key Left previous-window

# Toggle last window
bind-key Tab last-window
