call pathogen#infect('bundle/{}')
set term=xterm
set guifont=Monospace\ 15
set background=dark
if has('gui_running')
  colorscheme solarized
else
  colorscheme default
endif
set guioptions-=e
set guioptions-=m
set guioptions-=r
set guioptions-=l
set guioptions-=T
set guioptions+=c
set wrap
set whichwrap+=<
set whichwrap+=>
set title
set showcmd
set showmode
set number
set ls=2
set modeline
set colorcolumn=72
set textwidth=72
set encoding=utf-8
set backspace=indent,eol,start
set wildmode=longest,list
set wildmenu
set expandtab
set nostartofline
set nosmartindent
set nosmarttab
set nocindent
set showtabline=2
set list listchars=eol:¬,tab:»\ ,trail:·
set showmatch
set hlsearch
set incsearch
let mapleader = ","

" Delete buffer while keeping window layout (don't close buffer's windows).
" Version 2008-11-18 from http://vim.wikia.com/wiki/VimTip165
if v:version < 700 || exists('loaded_bclose') || &cp
  finish
endif
let loaded_bclose = 1
if !exists('bclose_multiple')
  let bclose_multiple = 1
endif

" Display an error message.
function! s:Warn(msg)
  echohl ErrorMsg
  echomsg a:msg
  echohl NONE
endfunction

" Command ':Bclose' executes ':bd' to delete buffer in current window.
" The window will show the alternate buffer (Ctrl-^) if it exists,
" or the previous buffer (:bp), or a blank buffer if no previous.
" Command ':Bclose!' is the same, but executes ':bd!' (discard changes).
" An optional argument can specify which buffer to close (name or number).
function! s:Bclose(bang, buffer)
  if empty(a:buffer)
    let btarget = bufnr('%')
  elseif a:buffer =~ '^\d\+$'
    let btarget = bufnr(str2nr(a:buffer))
  else
    let btarget = bufnr(a:buffer)
  endif
  if btarget < 0
    call s:Warn('No matching buffer for '.a:buffer)
    return
  endif
  if empty(a:bang) && getbufvar(btarget, '&modified')
    call s:Warn('No write since last change for buffer '.btarget.' (use :Bclose!)')
    return
  endif
  " Numbers of windows that view target buffer which we will delete.
  let wnums = filter(range(1, winnr('$')), 'winbufnr(v:val) == btarget')
  if !g:bclose_multiple && len(wnums) > 1
    call s:Warn('Buffer is in multiple windows (use ":let bclose_multiple=1")')
    return
  endif
  let wcurrent = winnr()
  for w in wnums
    execute w.'wincmd w'
    let prevbuf = bufnr('#')
    if prevbuf > 0 && buflisted(prevbuf) && prevbuf != w
      buffer #
    else
      bprevious
    endif
    if btarget == bufnr('%')
      " Numbers of listed buffers which are not the target to be deleted.
      let blisted = filter(range(1, bufnr('$')), 'buflisted(v:val) && v:val != btarget')
      " Listed, not target, and not displayed.
      let bhidden = filter(copy(blisted), 'bufwinnr(v:val) < 0')
      " Take the first buffer, if any (could be more intelligent).
      let bjump = (bhidden + blisted + [-1])[0]
      if bjump > 0
        execute 'buffer '.bjump
      else
        execute 'enew'.a:bang
      endif
    endif
  endfor
  execute 'bdelete'.a:bang.' '.btarget
  execute wcurrent.'wincmd w'
endfunction
command! -bang -complete=buffer -nargs=? Bclose call s:Bclose('<bang>', '<args>')
nnoremap <silent> <Leader>bd :Bclose<CR>

" Given file size in bytes, return a human readable string
function! HumanReadableSize(size)
    let size = a:size
    let suffixes = ['', 'K', 'M', 'G']
    let i = 0
    while size > 1024
        let size = size / 1024.0
        let i = i + 1
    endwhile
    return printf("%.f%s", size, suffixes[i])
endfunction

" custom statusline
set statusline=\  " clear
set statusline+=%03.03n\  " buffer number
set statusline+=%{HumanReadableSize(getfsize(expand('%%:p')))}\  " file size
set statusline+=%{fugitive#statusline()}\  " git branch (requires VimFugitive)
set statusline+=%-.50F\  " file name
set statusline+=%r\  " read-only flag '[RO]'
set statusline+=%= " invisible separator
set statusline+=%l/%L\  " current line / total line count
set statusline+=%c\  " current column

syntax on
filetype plugin indent on
runtime! synmenu.vim
au BufRead * se formatoptions=q
au BufNewFile,BufRead *.thrift set filetype=thrift
au BufNewFile,BufRead *.clj set filetype=clojure
au BufNewFile,BufRead *.cljs set filetype=clojure

" tab spacing by file type
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType java setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType xml setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType html setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType json setlocal tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType javascript setlocal tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType css setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType clojure setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType thrift setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType markdown setlocal tabstop=4 shiftwidth=4 softtabstop=4

" highlight trailing whitespace
highlight TrailingWhiteSpace ctermbg=red guibg=red
autocmd BufWinEnter * match TrailingWhitespace /\s\+$/
autocmd InsertEnter * match TrailingWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match TrailingWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" this function was written by John McFarlane https://github.com/jmcfarlane
function! Stripws()
    normal mZ
    %s/\s\+$//e
    if line("'Z") != line(".")
        echo "Stripped whitespace\n"
    endif
    normal `Z
endfunction

" Settings for VimClojure
let vimclojure#HightlightBuiltins=1 " highlight Clojure's builtins
let vimclojure#ParenRainbow=1 " rainbow parentheses
let vimclojure#DynamicHighlighting=1 " dynamically highlight functions

" binding for NERDTree
command NT NERDTreeToggle

" increase index capacity for ctrlp
let ctrlp_max_files=10000000
