# map right command button on my MacBook to middle mouse
xmodmap -e "keycode 134 = Pointer_Button2"
xkbset m

xsetroot -cursor_name crosshair

# http://superuser.com/questions/371321/xmonad-focused-window-border-issues-with-virtualbox-vmware-guest-additions
xcompmgr & 
exec xmonad
